# Utiliser une image de base légère Python
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires dans l'image
COPY requirements.txt .
COPY frontend.py .
COPY templates/ templates/
COPY static/ static/

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port Flask
EXPOSE 5000

# Commande pour démarrer l'application
CMD ["python", "frontend.py"]